### ISSUE TITLE
How to migrate from `pow_mailer_layout` to `pow_mailer_layouts`

### ISSUE THREAD

**Issue by nikcorg** [pow-auth/pow#727]
Hello!

I spotted a warning mentioning that `pow_mailer_layout` had been deprecated and it is indeed even in the [changelog](https://hexdocs.pm/pow/CHANGELOG.html#deprecations-1).

Are there migration instructions anywhere to moving from the old to the new?

**Comment by danschultzer** [comment]
Yeah, I should have added more to that changelog. Updated both the changelog and the warning with #730, thanks!

This was part of moving towards Phoenix 1.7 syntax changes, so it follows the same rules. Instead of:

```elixir
put_private(conn, :pow_mailer_layout, {MyAppWeb.LayoutView, :email})
```

You would do something like:

```elixir
put_private(conn, :pow_mailer_layouts, html: {MyAppWeb.Layouts, :email}, text: false

# If you use layout for text
put_private(conn, :pow_mailer_layouts, html: {MyAppWeb.Layouts, :email}, text: {MyAppWeb.Layouts, :email_text}
```

The `Layouts` module may look something like:

```elixir
defmodule MyAppWeb.Layouts do
  @moduledoc false
  use MyAppWeb, :html

  embed_templates "layouts/*.html"

  # If you use layout for text
  embed_templates "layouts/*.text", suffix: "_text"
end
```

You can see how text email uses a suffix to avoid conflicts with the `embed_templates`. This is so we can use the Phoenix HTML helpers. You could also split it in two separate modules (one for HTML emails and one for text emails).
